In [6]:
import os, pandas as pd

In [7]:
cd C:\Users\tr432\Downloads

C:\Users\tr432\Downloads

In [8]:
## (선택1 : 리눅스 상의 fastq 파일명을 엑셀 열 하나에 복붙한 파일 사용) fastq 파일명을 forward / reverse로 나누기

dir_in_linux = "/home/sejong/Desktop/TaehunRoh/Run45/0.RawData/Run45_fastq"  #Edit: fastq 파일이 실제로 있는 폴더 (파일경로에 사용자명까지 들어가야됨)

df = pd.read_excel("manifest_Crop_0.xlsx", header=None)  #Edit: 파일명 한줄로 복붙해놓은 엑셀파일 넣어야됨

# 첫 번째 열을 파일명 열로 사용
df["file"] = df.iloc[:, 0]

# [fastq 파일 경로 + / + fastq 파일명] 형태로 붙이기
df["path"] = dir_in_linux + "/" + df["file"]

# Paired-end : _R1_ / _R2_ 여부로 forward / reverse 채우기
df["forward-absolute-filepath"] = df["path"].where(df["file"].astype(str).str.contains("_R1_"), "")
df["reverse-absolute-filepath"] = df["path"].where(df["file"].astype(str).str.contains("_R2_"), "")

# Single-end : single-end의 경우엔 absolute-filepath 하나만 필요함
df["absolute-filepath"] = df["path"].where(~df["file"].astype(str).str.contains("_R1_|_R2_"), "")

df

,0,file,path,forward-absolute-filepath,reverse-absolute-filepath,absolute-filepath
0,0-1_S1_L001_R1_001.fastq.gz,0-1_S1_L001_R1_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,
1,0-1_S1_L001_R2_001.fastq.gz,0-1_S1_L001_R2_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,
2,0-2_S2_L001_R1_001.fastq.gz,0-2_S2_L001_R1_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,
3,0-2_S2_L001_R2_001.fastq.gz,0-2_S2_L001_R2_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,
4,0-3_S3_L001_R1_001.fastq.gz,0-3_S3_L001_R1_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,
...,...,...,...,...,...,...
330,V10-0w_S127_L001_R2_001.fastq.gz,V10-0w_S127_L001_R2_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,
331,V10-1w_S136_L001_R1_001.fastq.gz,V10-1w_S136_L001_R1_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,
332,V10-1w_S136_L001_R2_001.fastq.gz,V10-1w_S136_L001_R2_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,
333,V10-2w_S145_L001_R1_001.fastq.gz,V10-2w_S145_L001_R1_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,
334,V10-2w_S145_L001_R2_001.fastq.gz,V10-2w_S145_L001_R2_001.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,

In [4]:
## (선택2 : fastq 파일이 실제로 들어있는 폴더명에서 파일명 가져옴) fastq 파일명을 forward / reverse로 나누기

dir_in_linux = '/home/sejong/Desktop/TaehunRoh/Run45/0.RawData/Run45_fastq'  #Edit: fastq 파일이 실제로 있는 폴더 (파일경로에 사용자명까지 들어가야됨)

# fastq 파일 분류
files = [f for f in os.listdir()
         if f.endswith((".fastq.gz"))]  #Edit: 또는 ".fastq" 로 변경

df = pd.DataFrame({"file": files})

# [fastq 파일 경로 + / + fastq 파일명] 형태로 붙이기
df["path"] = dir_in_linux + "/" + df["file"]

# Paired-end : _R1_ / _R2_ 여부로 forward / reverse 채우기
df["forward-absolute-filepath"] = df["path"].where(df["file"].str.contains("_R1_"), "")
df["reverse-absolute-filepath"] = df["path"].where(df["file"].str.contains("_R2_"), "")

# Single-end : single-end의 경우엔 absolute-filepath 하나만 필요함
df["absolute-filepath"]         = df["path"].where(~df["file"].str.contains("_R1_|_R2_"), "")

df

,file,path,forward-absolute-filepath,reverse-absolute-filepath,absolute-filepath
0,SRR22515467.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
1,SRR22515468.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
2,SRR22515469.fastq.gz,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,,,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...

In [ ]:
## 메타데이터 불러와서 sample-id 열 만들기

meta = pd.read_csv('RUN45_Metadata_rev_Crop.txt', sep="\t", dtype=str)  #Edit: 원하는 샘플 데이터만 필터링 돼있는 메타데이터를 써야됨

rows = []
for sid in meta["#SampleID"]:
    row = {"sample-id": sid}

    m_f = df[df["file"].astype(str).str.startswith(sid + "_")]  ## "#SampleID" 에 "_" 를 넣어놔도 BBH 측에선 "-" 로 바꿔놓음. 그래서 fastq 파일명에서 "_" 가 처음 나오는 지점 앞부분까지가 샘플명이 됨.
    row["forward-absolute-filepath"] = "" if m_f.empty else m_f["forward-absolute-filepath"].iloc[0]

    m_r = df[df["file"].astype(str).str.startswith(sid + "_")]
    row["reverse-absolute-filepath"] = "" if m_r.empty else m_r["reverse-absolute-filepath"].iloc[1]

    m_single = df[df["file"].astype(str).str.startswith(sid + "_")]
    row["absolute-filepath"] = "" if m_single.empty else m_single["reverse-absolute-filepath"].iloc[0]

    rows.append(row)

manifest = pd.DataFrame(
    rows,
    columns=["sample-id",
             "forward-absolute-filepath",
             "reverse-absolute-filepath"]  ## paired-end 인 경우에 사용
#    columns=["sample-id",
#             "absolute-filepath"]  ## single-end 인 경우에 사용
)

manifest.to_csv("manifest_Crop_python.tsv", sep="\t", index=False)

manifest

,sample-id,forward-absolute-filepath,reverse-absolute-filepath
0,0-1,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
1,0-2,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
2,0-3,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
3,A-1,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
4,A-2,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
...,...,...,...
97,RB-U-2,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
98,RB-U-3,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
99,RB-U-D1,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
100,RB-U-D2,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...
101,RB-U-D3,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...,/home/sejong/Desktop/TaehunRoh/Run45/0.RawData...

In [10]:
## 메타데이터의 샘플수랑 manifest 파일의 샘플수가 같은지 확인용

print(meta.shape[0])
print(manifest.shape[0])

102
102

In [11]:
## 중복되는 파일경로 있는지 확인용

# forward 파일경로가 중복되는 행들
dup_f = manifest[manifest["forward-absolute-filepath"].duplicated(keep=False)]
print("=== duplicated forward-absolute-filepath ===")
print(dup_f)

print("\n")

# reverse 파일경로가 중복되는 행들
dup_r = manifest[manifest["reverse-absolute-filepath"].duplicated(keep=False)]
print("=== duplicated reverse-absolute-filepath ===")
print(dup_r)

=== duplicated forward-absolute-filepath ===
Empty DataFrame
Columns: [sample-id, forward-absolute-filepath, reverse-absolute-filepath]
Index: []


=== duplicated reverse-absolute-filepath ===
Empty DataFrame
Columns: [sample-id, forward-absolute-filepath, reverse-absolute-filepath]
Index: []